# -*- coding: utf-8 -*-
"""finalproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_oR7qKFFY2_F_v-OhsfnTZ7Ess4TyTkg
"""

# 安裝套件 + 授權
!pip install gspread oauth2client pandas --quiet
from google.colab import auth
auth.authenticate_user()
import gspread
from google.auth import default
import pandas as pd

# 連接Google Sheets
creds, _ = default()
gc = gspread.authorize(creds)
SHEET_ID = "1-pDPG2b4HJR9C8X6YGaflROWTq2ZqgSvN5jKaoQ5crU"
sh = gc.open_by_key(SHEET_ID)


# 自動抓Form回應Sheet
def get_form_sheet(sh):
    for ws in sh.worksheets():
        title = ws.title.lower()
        if "form" in title and "response" in title:
            return ws
    return sh.get_worksheet(0)

form_sheet = get_form_sheet(sh)


# 讀資料
data = form_sheet.get_all_records()
df = pd.DataFrame(data)

df.columns = [c.strip() for c in df.columns]


# 找欄位
def find_combined_col(df):
    for c in df.columns:
        if "異動" in c or "項目" in c:
            return c
    return None

combined_col = find_combined_col(df)

if combined_col is None:
    raise ValueError("❌ 找不到合併欄位（類型-品項-數量）")

print("使用欄位：", combined_col)

# split
def parse_item(text):
    parts = str(text).split("-")

    if len(parts) != 3:
        raise ValueError(f"❌ 格式錯誤：{text}（應為 類型-品項-數量）")

    action = parts[0].strip()
    item = parts[1].strip()
    qty_str = parts[2].strip()

    if not qty_str.isdigit():
        raise ValueError(f"❌ 數量不是數字：{qty_str}")

    qty = int(qty_str)

    return action, item, qty


# 解析資料
parsed = df[combined_col].apply(parse_item)
df["異動類別"] = parsed.apply(lambda x: x[0])
df["品項"] = parsed.apply(lambda x: x[1])
df["數量"] = parsed.apply(lambda x: x[2])

# 庫存計算
def convert(row):
    if row["異動類別"] in ["歸還", "上架"]:
        return row["數量"]
    elif row["異動類別"] in ["借出", "報廢"]:
        return -row["數量"]
    else:
        return 0

df["signed_qty"] = df.apply(convert, axis=1)


# 計算庫存
inventory = df.groupby("品項")["signed_qty"].sum().reset_index()
inventory.columns = ["品項", "目前庫存"]
inventory = inventory.sort_values("品項")

# 寫回Inventory Sheet
try:
    inv_sheet = sh.worksheet("Inventory")
except:
    inv_sheet = sh.add_worksheet(title="Inventory", rows=100, cols=10)

inv_sheet.clear()

inv_sheet.update(
    [inventory.columns.tolist()] + inventory.values.tolist()
)


# 輸出結果
print("✔ 更新完成")

print("\n📦 庫存：")
display(inventory)

print("\n⚠️ 庫存異常：")
display(inventory[inventory["目前庫存"] < 0])

print("\n📌 最近 10 筆紀錄：")
display(df.tail(10))