# -*- coding: utf-8 -*-
"""finalproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_oR7qKFFY2_F_v-OhsfnTZ7Ess4TyTkg
"""

# 安裝套件 + 授權
!pip install gspread google-auth
from google.colab import auth
auth.authenticate_user()
import gspread
from google.auth import default

# 連接Google Sheets
creds, _ = default()
gc = gspread.authorize(creds)
sheet_id = "1-pDPG2b4HJR9C8X6YGaflROWTq2ZqgSvN5jKaoQ5crU"
sh = gc.open_by_key(sheet_id)
ws = sh.get_worksheet(0)

# 建立庫存資料
inventory = {
    "馬達": {
        "IG-32PGM": 5,
        "IG-36PGM": 2,
        "IG-40PGM": 4,
        "RB-37GM": 4,
        "RB-40GM": 2,
        "TT motor": 10
    },
    "電控": {
        "Arduino Nano": 5,
        "Arduino UNO": 4,
        "Arduino Mega": 2,
        "ESP32": 6,
        "Jetson Orin": 0,
        "Jetson Nano": 1
    }
}

# parse
def parse(text):
    parts = text.split("-")

    if len(parts) < 3:
        raise ValueError(f"❌ 格式錯誤：{text}")

    cat = parts[0].strip()
    qty = int(parts[-1])
    item = "-".join(parts[1:-1]).strip()

    return cat, item, qty


# update
def update(inv, action, cat, item, qty):

    if cat not in inv:
        inv[cat] = {}

    if action == "借出零件":
        if item in inv[cat]:
            if inv[cat][item] - qty >= 0:
                inv[cat][item] -= qty
            else:
                print(f"⚠️ 借出失敗：{item} 庫存不足")
        else:
            print(f"⚠️ 品項不存在：{item}")

    elif action == "歸還零件":
        if item in inv[cat]:
            inv[cat][item] += qty
        else:
            print(f"⚠️ 歸還失敗：{item} 不存在")

    elif action == "上架零件":
        if item in inv[cat]:
            inv[cat][item] += qty
        else:
            inv[cat][item] = qty

    elif action == "報廢零件":
        if item in inv[cat]:
            if inv[cat][item] - qty >= 0:
                inv[cat][item] -= qty
            else:
                print(f"⚠️ 報廢失敗：{item} 庫存不足")
        else:
            print(f"⚠️ 品項不存在：{item}")

    return inv

# 讀取資料
data = ws.get_all_values()

for row in data[1:]:
    if len(row) < 3:
        continue

    action = row[1]
    text = row[2]

    try:
        cat, item, qty = parse(text)
        inventory = update(inventory, action, cat, item, qty)

    except:
        pass

# 轉文字
def to_text(inv):
    text = "📦 倉儲狀態\n\n"

    for cat, items in inv.items():
        text += cat + "\n"

        for k, v in items.items():
            text += f"{k} (剩餘：{v})\n"

        text += "\n"

    return text

result = to_text(inventory)

# 寫回 E1
ws.update("E1", [[result]])
print("✅ 完成更新 E1")