# -*- coding: utf-8 -*-
"""排版.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17TTa7TnxGWicfuFouC19PZdaR4thBAvl
"""

# ======================= 安裝套件 + Google 驗證 =======================
!pip install gspread google-auth
from google.colab import auth
auth.authenticate_user()
import gspread
from google.auth import default


# ======================= 連接 Google Sheets =======================
creds, _ = default() # 取得 Google 驗證資訊
gc = gspread.authorize(creds) # 建立 gspread client
sheet_id = "1-pDPG2b4HJR9C8X6YGaflROWTq2ZqgSvN5jKaoQ5crU" # Google Sheets ID
sh = gc.open_by_key(sheet_id) # 開啟 Google Sheets
ws = sh.get_worksheet(0) # 取得第一個工作表準備讀


# ======================= 初始庫存資料 =======================
inventory = {
    "馬達": {
        "IG-32PGM": 5,
        "IG-36PGM": 2,
        "IG-40PGM": 4,
        "RB-37GM": 4,
        "RB-40GM": 2,
        "TT motor": 10
    },
    "電控": {
        "Arduino Nano": 5,
        "Arduino UNO": 4,
        "Arduino Mega": 2,
        "ESP32": 6,
        "Jetson Orin": 0,
        "Jetson Nano": 1
    },
    "皮帶": {
        "175W9": 1,
        "275w9": 4,
        "295w9": 2,
        "300w9": 2,
        "420w9": 4,
        "450w9": 1,
        "465w9": 3,
        "260W15": 4,
        "295w15": 2,
        "320w15": 4,
        "375w15": 2,
        "420w15": 1,
        "450w15": 2,
        "475w15": 2,
        "500w15": 5
    },
    "Gear":{
        "16T": 4,
        "20T": 3,
        "24T": 4,
        "40T": 6,
        "42T": 1,
        "48T": 3,
        "50T": 5,
        "62T": 2,
        "66T": 2
    }
}


# ======================= parse =======================
# 將表單輸入的字串拆解成：類別 / 品項 / 數量
def parse(text):
    parts = text.split("-")  # 用 "-" 分割字串

    if len(parts) < 3:
        raise ValueError(f"❌ 格式錯誤：{text}")

    cat = parts[0].strip() # 類別 = 第一段
    qty = int(parts[-1]) # 數量 = 最後一段
    item = "-".join(parts[1:-1]).strip() # 使用 join 是因為品項可能本身包含 "-"

    return cat, item, qty


# ======================= update =======================
# 根據操作類型更新 inventory
def update(inv, action, cat, item, qty):

    if cat not in inv: # 如果類別不存在，自動建立
        inv[cat] = {}

# 借出零件 ==============================================
    if action == "借出零件":
        if item in inv[cat]:
            if inv[cat][item] - qty >= 0:
                inv[cat][item] -= qty
            else:
                print(f"⚠️ 借出失敗：{item} 庫存不足")
        else:
            print(f"⚠️ 品項不存在：{item}")

# 歸還零件 ==============================================
    elif action == "歸還零件":
        if item in inv[cat]:
            inv[cat][item] += qty
        else:
            print(f"⚠️ 歸還失敗：{item} 不存在")

# 上架零件 ==============================================
    elif action == "上架零件":
        if item in inv[cat]:
            inv[cat][item] += qty # 若品項已存在，增加數量
        else:
            inv[cat][item] = qty # 若品項不存在，建立新品項

# 報廢零件 ==============================================
    elif action == "報廢零件":
        if item in inv[cat]:
            if inv[cat][item] - qty >= 0:
                inv[cat][item] -= qty
            else:
                print(f"⚠️ 報廢失敗：{item} 庫存不足")
        else:
            print(f"⚠️ 品項不存在：{item}")

    return inv



# ======================= 從 Google Sheets 讀取所有資料 =======================
data = ws.get_all_values()

# 逐筆處理表單紀錄
for row in data[1:]:
    if len(row) < 3:
        continue

    action = row[1]
    text = row[2]

    try:
        cat, item, qty = parse(text) # 解析資料
        inventory = update(inventory, action, cat, item, qty) # 更新庫存

    except:
        pass



# ======================= to_text() 轉文字 =======================
# 將 inventory dict 轉成文字報表
def to_text(inv):
    text = "📦 倉儲狀態\n\n"

    for cat, items in inv.items(): # 逐類別輸出
        text += cat + "\n"

        for k, v in items.items(): # 逐品項輸出
            text += f"{k} (剩餘：{v})\n"

        text += "\n"

    return text

result = to_text(inventory) # 產生倉儲狀態文字



# ======================= 將結果寫回 Google Sheets 的 E1 =======================
ws.update("E1", [[result]])
print("✅ 完成更新 E1")